# crossing1_area 顺时针多边形区域的各个顶点坐标
crossing1_area:
  [
    [ 591, 443 ],
    [ 815, 335 ],
    [ 2543, 813 ],
    [ 2553, 1275 ],
    [ 1727, 1270 ],
    [ 1731, 1430 ],
    [ 1274, 1436 ],
    [ 372, 537 ]
  ]
crossing1_classes:
  ['h','o','k','b']
# 道口二开启时防区
crossing2_area_k:
  [
    [ 17, 831 ],
    [ 898, 383 ],
    [ 1419, 480 ],
    [ 1120, 1067 ]
  ]
# 道口二闭合时防区
crossing2_area_b:
  [
    [ 17, 831 ],
    [ 591, 594 ],
    [ 1307, 698 ],
    [ 1120, 1067 ]
  ]
crossing2_classes:
  [ 'h','o','k','b' ]

# 道口三开启时防区
crossing3_area_k:
 [
  [ 12, 631 ],
  [ 953, 485 ],
  [ 1535, 496 ],
  [ 1088, 1010 ],
  [ 9, 1011 ]
  ]
# 道口三闭合时防区
crossing3_area_b:
  [
    [ 12, 631 ],
    [ 501, 555 ],
    [ 1399, 662 ],
    [ 1040, 1019 ],
    [ 17, 1019 ]
  ]
crossing2_classes:
  [ 'h','o','k','b' ]